[project]
title = "Student Score Analyser"
version = "0.1.0"
port = 8501
slug = "student-score-analyser"  
entrypoint = "main.py"    

[branding]
name = "Student Score Analyser"
logo = "images/student_logo.png"
favicon = "images/favicon.ico"
primaryColor = "#2D9CDB"

[data.sample_csv]
type = "csv"
path = "data/student-scores.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"